spring:
  datasource:
    url: jdbc:h2:file:/home/jeremy/.avokeeper/db
    username: SA
    password: 
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema.sql
  jpa:
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG
      zaxxer:
        hikari: DEBUG